const express = require('express');
const router = express.Router();
const { getAll, getOne, create, update, remove } = require('../controllers/womanController');
const { protect } = require('../middleware/auth');
router.use(protect);
router.get('/', getAll);
router.post('/', create);
router.get('/:id', getOne);
router.put('/:id', update);
router.delete('/:id', remove);
module.exports = router;
